############################
## CHANGE THESE
############################

baseURL: 'https://computerrivet.github.io'
title: 'Simple is Complex'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


