############################
## CHANGE THESE
############################

baseURL: 'https://computerrivet.github.io/computerrivet.github.io'
title: computerrivet.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


