############################
## Navbar
############################

main:
  - name: Home
    url: /
    weight: 10
  - name: Resume
    url: /Wade-Johnson-Resume.pdf
    weight: 20
  - name: About
    url: /about/
    weight: 30
