############################
## Author
############################

author:
  name: "Wade Johnson"
  image: author.jpeg
  greeting: "Welcome to my site!"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/computerrivet
  # - gitlab: 
  #- facebook: https://github.com/computerrivet/qubt
  # - x-twitter:
  # - mastodon:
  - linkedin: https://www.linkedin.com/in/wade-johnson-785925a/
  #- instagram: https://github.com/computerrivet/L1nkr
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: 'mailto:computerrivet@gmail.com'
  - website: 'https://computerrivet.github.io'
  # - link: 
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  # - keybase: 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "Qubt Theme"
description: "Demo site build with Qubt & Hugo"
images:
  - thumbnail.jpeg